kind: pipeline
name: default

steps:
- name: docker-mirror
  image: docker:git
  volumes:
  - name: docker
    path: /var/run/
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - git diff --unified=0 ./mirror-images/*.txt | grep '^+[a-zA-Z0-9]' | cut -c 2- | ./scripts/docker-pull-pusher.sh
  settings:
    custom_dns: 1.1.1.1
  when:
    ref:
      include:
      - "refs/heads/master"
    event:
    - push

volumes:
- name: docker
  host:
    path: /var/run/
